language: objective-c

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReSwiftRouter"
    - UPDATE_DOCS="false"

osx_image: xcode10

matrix:
  include:
    - env: SCHEME="macOS"  SDK="macosx10.14"          DESTINATION="arch=x86_64"
    - env: SCHEME="iOS"    SDK="iphonesimulator12.0"  DESTINATION="OS=12.0,name=iPhone X"
    - env: SCHEME="tvOS"   SDK="appletvsimulator12.0"  DESTINATION="OS=10.2,name=Apple TV 1080p"

before_install:
  - carthage bootstrap --platform "$SCHEME" --verbose

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J ReSwiftRouter
